dist: trusty
language: python
cache: 
  pip: true
  yarn: true
  directories:
    - ~/miniconda
addons:
  chrome:
    stable
  apt:
    packages:
      - libenchant-dev

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.5"
  - "3.6"

before_install:
  - docker pull lukasmartinelli/hadolint
  - nvm install node
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - google-chrome-stable --version
  - node --version
  - yarn --version
  - yarn global add eslint babel-eslint eslint-plugin-react
  - export PATH="$HOME/miniconda/bin:$PATH"
  - if ! hash conda 2>/dev/null; then
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    rm -r ~/miniconda;
    bash miniconda.sh -b -p $HOME/miniconda;
    fi
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
    # Useful for debugging any issues with conda
  - conda info -a
  - if ! source activate test-environment; then
    conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION;
    source activate test-environment;
    fi
  - pip install --upgrade pip
  - pip install -r test-requirements.txt --progress-bar=off
  - wget https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - chmod +x chromedriver
  - mv -f chromedriver $HOME/.yarn/bin
  - wget https://github.com/errata-ai/vale/releases/download/v0.11.2/vale_0.11.2_Linux_64-bit.tar.gz
  - tar xvf vale_0.11.2_Linux_64-bit.tar.gz

script:
  - docker run --rm -i lukasmartinelli/hadolint hadolint --ignore DL3008 --ignore DL3013 - < Dockerfile
  - make eslint
  - cd doc && make spelling && cd ..
  - ./vale --glob='*.rst' doc
  - make checkdocs
  - make test

after_success:
  - codecov
